<?php /*///////////////// AUTHOR INFO //////////////
		//// NAME: ZEEQ                         ////
		//// WEBSITE: www.hzcreative.com        ////
		//// EMAIL: me.hzcreative@gmail.com     ////
		////////////////////////////////////////////*/ ?>
<div class="pt-settings-stage">
<div class="ctl">
    <label>
      <input type="checkbox" id="chk_labeling" name="chk_labeling" value="true" <?php if(get_post_meta($post->ID,'chk_labeling',true)): ?>checked="checked"<?php endif; ?> />
      Enable Labeling <br />
<small>First column will react as labels.</small></label>
  </div>
  <div class="ctl">
    <label>Title Text</label>
    <input type="text" name="ptlbTitle" id="ptlbTitle" value="<?php echo get_post_meta($post->ID,'ptlbTitle',true); ?>"  />
  </div>
  <div class="ctl">
    <label>Title Vertical Spacing: <span id="lbl_lbVSpacing"></span>px</label>
    <div id="pt_slider_lbVSpacing"></div>
  </div>
  <div class="ctl">
    <label>Title Horizontal Spacing: <span id="lbl_lbHSpacing"></span>px</label>
    <div id="pt_slider_lbHSpacing"></div>
  </div>
   <div class="ctl">
    <label>Title Line Height: <span id="lbl_lbLineHeight"></span>px</label>
    <div id="pt_slider_lbLineHeight"></div>
  </div>
</div>
<strong>Title Font</strong>
<div class="pt-settings-stage">
  <?php $attr = array('var'=>'ptStyles','ctl'=>'lbTitle'); include('ctl.font.phtml'); ?>
</div>
<strong>Features</strong>
<div class="pt-settings-stage">
<div class="ctl">
    <label>BG Color: </label>
    <input type="text" name="pt_lbFeaturesBGColor" id="pt_lbFeaturesBGColor" class="pt_cp" sid='lbFeaturesBGColor' value="" />
  </div>
  <div class="ctl">
    <label>Test Align: </label>
    <select id="select_lbTextAlign" name="select_lbTextAlign">
          <option value="left">Left</option>
          <option value="center">Center</option>
          <option value="right" >Right</option>
	</select>
        
  </div>
  <?php $attr = array('var'=>'ptStyles','ctl'=>'lbFeature'); include('ctl.font.mini.phtml'); ?>
</div>
<script language="JavaScript" type="text/javascript">
function setMyPriceTableLabeling(){
	jQuery("#ptStyles").val(JSON.stringify(ptStyles));
	jQuery('#select_lbTextAlign').val(ptStyles.lbTextAlign);
	jQuery("#lbl_lbVSpacing").text(ptStyles.lbVSpacing);
	jQuery("#lbl_lbHSpacing").text(ptStyles.lbHSpacing);
	jQuery("#lbl_lbLineHeight").text(ptStyles.lbLineHeight);
	jQuery("#chk_lbZebra").prop('checked',ptStyles.lbZebra);
	jQuery("#chk_lbZebraLight").prop('checked',ptStyles.lbZebraLight);


	
}

jQuery(document).ready(function(jQuery){
	jQuery('#select_lbTextAlign').change(function() {
  		ptStyles.lbTextAlign = jQuery(this).val(); 
			setMyPriceTableLabeling();
		});
	jQuery("#chk_lbZebra").click(function(){
			if(jQuery(this).prop('checked')){
				ptStyles.lbZebra = true;
			}else{ ptStyles.lbZebra = false; }
			setMyPriceTableLabeling();
		});
	jQuery("#chk_lbZebraLight").click(function(){
			if(jQuery(this).prop('checked')){
				ptStyles.lbZebraLight = true;
			}else{ ptStyles.lbZebraLight = false; }
			setMyPriceTableLabeling();
		});
	jQuery( "#pt_slider_lbVSpacing" ).slider({
			range: "min",
			value:ptStyles.lbVSpacing,
			min: 0,
			max: 100,
			slide: function( event, ui ) {
				ptStyles.lbVSpacing = ui.value;
				setMyPriceTableLabeling();
			}
		});
		jQuery( "#pt_slider_lbHSpacing" ).slider({
			range: "min",
			value:ptStyles.lbHSpacing,
			min: 0,
			max: 100,
			slide: function( event, ui ) {
				ptStyles.lbHSpacing = ui.value;
				setMyPriceTableLabeling();
			}
		});
		jQuery( "#pt_slider_lbLineHeight" ).slider({
			range: "min",
			value:ptStyles.lbLineHeight,
			min: 0,
			max: 100,
			slide: function( event, ui ) {
				ptStyles.lbLineHeight = ui.value;
				setMyPriceTableLabeling();
			}
		});
	setMyPriceTableLabeling();
});
</script>