<?php /*///////////////// AUTHOR INFO //////////////
		//// NAME: ZEEQ                         ////
		//// WEBSITE: www.hzcreative.com        ////
		//// EMAIL: me.hzcreative@gmail.com     ////
		////////////////////////////////////////////*/ ?>
<div class="pt-settings-stage">
<div class="ctl">
    <label>Column Outer Spacing: <span id="lbl_columnOuterSpacing"></span>px</label>
    <div id="pt_slider_columnOuterSpacing"></div>
  </div>
  <div class="ctl">
    <label>Column Inner Spacing: <span id="lbl_columnInnerSpacing"></span>px</label>
    <div id="pt_slider_columnInnerSpacing"></div>
  </div>
  <div class="ctl">
    <label>Column Background Color: </label>
    <input type="text" name="pt_col_bgcolor" id="pt_col_bgcolor" class="pt_cp" sid='columnBGColor' value="" />
  </div>
  <div class="ctl">
    <label>Column Hover Color: </label>
    <input type="text" name="pt_col_bgcolor_hover" id="pt_col_bgcolor_hover" class="pt_cp" sid='columnBGColorHover' value="" />
  </div>
  <div class="ctl">
    <label>
      <input type="checkbox" id="chk_columnRoundedCorner" />
      Rounded Corners</label>
  </div>
  <div class="ctl">
    <label>Rounded Corner Radius: <span id="lbl_columnRoundedCornerRadius"></span>px</label>
    <div id="pt_slider_columnRoundedCornerRadius"></div>
  </div>
  <div class="ctl">
    <label>
      <input type="checkbox" id="chk_columnRoundedCornerStyle" />
      Apply to all columns</label>
  </div>
</div>