<?php /*///////////////// AUTHOR INFO //////////////
		//// NAME: ZEEQ                         ////
		//// WEBSITE: www.hzcreative.com        ////
		//// EMAIL: me.hzcreative@gmail.com     ////
		////////////////////////////////////////////*/ ?>
<div class="pt-settings-stage">
<div class="ctl">
   <label>
      <input type="checkbox" name="chk_yesnoicon" value="true" <?php if(get_post_meta($post->ID,'ptyesnoicon',true)){ ?>checked="checked"<?php } ?> />
      Enable Yes No Icon</label>
  </div>
<div class="ctl">
    <label>Icon Size: <span id="lbl_ynIconSize"></span>px</label>
    <div id="pt_slider_ynIconSize"></div>
  </div>
</div>
<div class="pt-settings-stage">
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_1" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_1.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_2" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_2.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_3" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_3.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_4" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_4.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_5" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_5.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_6" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_6.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_7" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_7.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_8" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_8.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_9" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_9.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_10" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_10.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_11" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_11.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_12" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_12.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_13" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_13.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_14" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_14.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_15" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_15.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_16" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_16.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_17" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_17.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_18" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_18.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_19" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_19.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_20" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_20.png" />
     </label>
</div>
<div class="ctl">
<label>
      <input type="radio" name="yn_icon" value="yes_no_21" <?php if(get_post_meta($post->ID,'yn_icon',true)): ?>checked="checked"<?php endif; ?> />
      <img src="<?php echo PRICETABLE_URL; ?>images/yes_no_21.png" />
     </label>
</div>
</div>

<script language="JavaScript" type="text/javascript">
function setMyPriceTableYNIcon(){
	jQuery("#ptStyles").val(JSON.stringify(ptStyles));
	jQuery("#lbl_ynIconSize").text(ptStyles.ynIconSize);
	jQuery("input[value="+ptStyles.ynIcon+"]").prop('checked',true);
	
}
jQuery(document).ready(function(jQuery){
	
	jQuery('input[name=yn_icon]').click(function(){
		ptStyles.ynIcon = jQuery(this).val();
		setMyPriceTableYNIcon();
	});
	jQuery( "#pt_slider_ynIconSize" ).slider({
			range: "min",
			value:ptStyles.ynIconSize,
			min: 0,
			max: 32,
			slide: function( event, ui ) {
				ptStyles.ynIconSize = ui.value;
				setMyPriceTableYNIcon();
			}
		});
	
		setMyPriceTableYNIcon();
});
</script>