<?php /*///////////////// AUTHOR INFO //////////////
		//// NAME: ZEEQ                         ////
		//// WEBSITE: www.hzcreative.com        ////
		//// EMAIL: me.hzcreative@gmail.com     ////
		////////////////////////////////////////////*/ ?>
<div class="pt-settings-stage">
<div class="ctl">
    <label>
      <input type="checkbox" id="chk_featuresTransparent" value="true" />
      Transparent</label>
  </div>
<div class="ctl">
    <label>Background Color: </label>
    <input type="text" name="pt_featuresBGColor" id="pt_featuresBGColor" class="pt_cp" sid='featuresBGColor' value="" />
  </div>
<div class="ctl">
    <label>
      <input type="checkbox" id="chk_featuresSeparatorV" />
      Enable Vertical Separators</label>
  </div>
  <div class="ctl">
    <label>
      <input type="checkbox" id="chk_featuresSeparatorH" />
      Enable Horizontal Separators</label>
  </div>
  <div class="ctl">
    <label>Separators Opacity: <span id="lbl_featuresSeparatorOpacity"></span>%</label>
    <div id="pt_slider_featuresSeparatorOpacity"></div>
  </div>
  <div class="ctl">
    <label>Vertical Spacing: <span id="lbl_featuresSpacingV"></span>px</label>
    <div id="pt_slider_featuresSpacingV"></div>
  </div>
    <div class="ctl">
    <label>
      <input type="checkbox" id="chk_lbZebra" />
      Zebra Row Highlighter</label>
  </div>
  <div class="ctl">
    <label>
      <input type="checkbox" id="chk_lbZebraLight" />
      Zebra Highlighter Light</label>
  </div>
</div>
<strong>Font</strong>
<div class="pt-settings-stage">
  <?php $attr = array('var'=>'ptStyles','ctl'=>'columnFeatures'); include('ctl.font.phtml'); ?>
</div>
<script language="JavaScript" type="text/javascript">
function setMyPriceTableFeatures(){
	jQuery("#ptStyles").val(JSON.stringify(ptStyles));
	jQuery("#chk_featuresSeparatorV").prop('checked',ptStyles.featuresSeparatorV);
	jQuery("#chk_featuresSeparatorH").prop('checked',ptStyles.featuresSeparatorH);
	jQuery("#chk_featuresTransparent").prop('checked',ptStyles.featuresTransparent);
	jQuery("#lbl_featuresSeparatorOpacity").text(ptStyles.featuresSeparatorOpacity);
	jQuery("#lbl_featuresSpacingV").text(ptStyles.featuresSpacingV);
}

jQuery(document).ready(function(jQuery){
	jQuery("#chk_featuresTransparent").click(function(){
			if(jQuery(this).prop('checked')){
				ptStyles.featuresTransparent = true;
			}else{ ptStyles.featuresTransparent = false; }
			setMyPriceTableFeatures();
		});
	jQuery("#chk_featuresSeparatorV").click(function(){
			if(jQuery(this).prop('checked')){
				ptStyles.featuresSeparatorV = true;
			}else{ ptStyles.featuresSeparatorV = false; }
			setMyPriceTableFeatures();
		});
	jQuery("#chk_featuresSeparatorH").click(function(){
			if(jQuery(this).prop('checked')){
				ptStyles.featuresSeparatorH = true;
			}else{ ptStyles.featuresSeparatorH = false; }
			setMyPriceTableFeatures();
		});
	jQuery( "#pt_slider_featuresSeparatorOpacity" ).slider({
			range: "min",
			value:ptStyles.featuresSeparatorOpacity,
			min: 0,
			max: 100,
			step: 10,
			slide: function( event, ui ) {
				ptStyles.featuresSeparatorOpacity = ui.value;
				setMyPriceTableFeatures();
			}
		});
		jQuery( "#pt_slider_featuresSpacingV" ).slider({
			range: "min",
			value:ptStyles.featuresSpacingV,
			min: 0,
			max: 50,
			slide: function( event, ui ) {
				ptStyles.featuresSpacingV = ui.value;
				setMyPriceTableFeatures();
			}
		});
	setMyPriceTableFeatures();
});
</script>