<?php

$predone_layouts = array(
	'about'	=>	array(
		'name'	=>	'About',
		'options'	=>	array(
			'about-1'	=>	'About 1',
			'about-2'	=>	'About 2',
			'about-3'	=>	'About 3',
			'about-4'	=>	'About 4',
			'about-5'	=>	'About 5',
			'about-6'	=>	'About 6',
			'about-7'	=>	'About 7',
			'about-8'	=>	'About 8',
		),
	),
	'articles'	=>	array(
		'name'	=>	'Articles',
		'options'	=>	array(
			'articles-1'	=>	'Articles 1',
			'articles-2'	=>	'Articles 2',
			'articles-3'	=>	'Articles 3',
			'articles-4'	=>	'Articles 4',
			'articles-5'	=>	'Articles 5',
			'articles-6'	=>	'Articles 6',
			'articles-7'	=>	'Articles 7',
			'articles-8'	=>	'Articles 8',
		),
	),
	'contact'	=>	array(
		'name'	=>	'Contact',
		'options'	=>	array(
			'contact-1'	=>	'Contact 1',
			'contact-2'	=>	'Contact 2',
			'contact-3'	=>	'Contact 3',
			'contact-4'	=>	'Contact 4',
			'contact-5'	=>	'Contact 5',
			'contact-6'	=>	'Contact 6',
			'contact-7'	=>	'Contact 7',
			'contact-8'	=>	'Contact 8',
		),
	),
	'faq'	=>	array(
		'name'	=>	'FAQ',
		'options'	=>	array(
			'faq-1'	=>	'FAQ 1',
			'faq-2'	=>	'FAQ 2',
			'faq-3'	=>	'FAQ 3',
			'faq-4'	=>	'FAQ 4',
			'faq-5'	=>	'FAQ 5',
			'faq-6'	=>	'FAQ 6',
			'faq-7'	=>	'FAQ 7',
			'faq-8'	=>	'FAQ 8',
		),
	),
	'gallery'	=>	array(
		'name'	=>	'Gallery',
		'options'	=>	array(
			'gallery-1'	=>	'Gallery 1',
			'gallery-2'	=>	'Gallery 2',
			'gallery-3'	=>	'Gallery 3',
			'gallery-4'	=>	'Gallery 4',
			'gallery-5'	=>	'Gallery 5',
			'gallery-6'	=>	'Gallery 6',
			'gallery-7'	=>	'Gallery 7',
			'gallery-8'	=>	'Gallery 8',
		),
	),
	'home'	=>	array(
		'name'	=>	'Home',
		'options'	=>	array(
			'home-1'	=>	'Home 1',
			'home-2'	=>	'Home 2',
			'home-3'	=>	'Home 3',
			'home-4'	=>	'Home 4',
			'home-5'	=>	'Home 5',
			'home-6'	=>	'Home 6',
			'home-7'	=>	'Home 7',
			'home-8'	=>	'Home 8',
			'home-9'	=>	'Home 9',
			'home-10'	=>	'Home 10',
			'home-11'	=>	'Home 11',
			'home-12'	=>	'Home 12',
		),
	),
	'pricing'	=>	array(
		'name'	=>	'Pricing',
		'options'	=>	array(
			'pricing-1'	=>	'Pricing 1',
			'pricing-2'	=>	'Pricing 2',
			'pricing-3'	=>	'Pricing 3',
			'pricing-4'	=>	'Pricing 4',
			'pricing-5'	=>	'Pricing 5',
			'pricing-6'	=>	'Pricing 6',
			'pricing-7'	=>	'Pricing 7',
			'pricing-8'	=>	'Pricing 8',
		),
	),
	'product'	=>	array(
		'name'	=>	'Product',
		'options'	=>	array(
			'product-1'	=>	'Product 1',
			'product-2'	=>	'Product 2',
			'product-3'	=>	'Product 3',
			'product-4'	=>	'Product 4',
			'product-5'	=>	'Product 5',
			'product-6'	=>	'Product 6',
			'product-7'	=>	'Product 7',
			'product-8'	=>	'Product 8',
		),
	),
	'team'	=>	array(
		'name'	=>	'Team',
		'options'	=>	array(
			'team-1'	=>	'Team 1',
			'team-2'	=>	'Team 2',
			'team-3'	=>	'Team 3',
			'team-4'	=>	'Team 4',
			'team-5'	=>	'Team 5',
			'team-6'	=>	'Team 6',
			'team-7'	=>	'Team 7',
			'team-8'	=>	'Team 8',
		),
	),
	'testimonial'	=>	array(
		'name'	=>	'Testimonial',
		'options'	=>	array(
			'testimonial-1'	=>	'Testimonial 1',
			'testimonial-2'	=>	'Testimonial 2',
			'testimonial-3'	=>	'Testimonial 3',
			'testimonial-4'	=>	'Testimonial 4',
			'testimonial-5'	=>	'Testimonial 5',
			'testimonial-6'	=>	'Testimonial 6',
			'testimonial-7'	=>	'Testimonial 7',
			'testimonial-8'	=>	'Testimonial 8',
		),
	),
	'videos'	=>	array(
		'name'	=>	'Videos',
		'options'	=>	array(
			'videos-1'	=>	'Videos 1',
			'videos-2'	=>	'Videos 2',
			'videos-3'	=>	'Videos 3',
			'videos-4'	=>	'Videos 4',
			'videos-5'	=>	'Videos 5',
			'videos-6'	=>	'Videos 6',
			'videos-7'	=>	'Videos 7',
			'videos-8'	=>	'Videos 8',
		),
	),
);

$predone_layouts_content = array(
	'about-1'		=>	'about-1',
	'about-2'		=>	'about-2',
	'about-3'		=>	'about-3',
	'about-4'		=>	'about-4',
	'about-5'		=>	'about-5',
	'about-6'		=>	'about-6',
	'about-7'		=>	'about-7',
	'about-8'		=>	'about-8',
	'articles-1'	=>	'articles-1',
	'articles-2'	=>	'articles-2',
	'articles-3'	=>	'articles-3',
	'articles-4'	=>	'articles-4',
	'articles-5'	=>	'articles-5',
	'articles-6'	=>	'articles-6',
	'articles-7'	=>	'articles-7',
	'articles-8'	=>	'articles-8',
	'contact-1'		=>	'contact-1',		
	'contact-2'		=>	'contact-2',		
	'contact-3'		=>	'contact-3',		
	'contact-4'		=>	'contact-4',		
	'contact-5'		=>	'contact-5',		
	'contact-6'		=>	'contact-6',		
	'contact-7'		=>	'contact-7',		
	'contact-8'		=>	'contact-8',		
	'faq-1'			=>	'faq-1',
	'faq-2'			=>	'faq-2',
	'faq-3'			=>	'faq-3',
	'faq-4'			=>	'faq-4',
	'faq-5'			=>	'faq-5',
	'faq-6'			=>	'faq-6',
	'faq-7'			=>	'faq-7',
	'faq-8'			=>	'faq-8',
	'gallery-1'		=>	'gallery-1',	
	'gallery-2'		=>	'gallery-2',	
	'gallery-3'		=>	'gallery-3',	
	'gallery-4'		=>	'gallery-4',	
	'gallery-5'		=>	'gallery-5',	
	'gallery-6'		=>	'gallery-6',	
	'gallery-7'		=>	'gallery-7',	
	'gallery-8'		=>	'gallery-8',	
	'home-1'		=>	'home-1',
	'home-2'		=>	'home-2',
	'home-3'		=>	'home-3',
	'home-4'		=>	'home-4',
	'home-5'		=>	'home-5',
	'home-6'		=>	'home-6',
	'home-7'		=>	'home-7',
	'home-8'		=>	'home-8',
	'home-9'		=>	'home-9',
	'home-10'		=>	'home-10',
	'home-11'		=>	'home-11',
	'home-12'		=>	'home-12',
	'pricing-1'		=>	'pricing-1',
	'pricing-2'		=>	'pricing-2',
	'pricing-3'		=>	'pricing-3',
	'pricing-4'		=>	'pricing-4',
	'pricing-5'		=>	'pricing-5',
	'pricing-6'		=>	'pricing-6',
	'pricing-7'		=>	'pricing-7',
	'pricing-8'		=>	'pricing-8',	
	'product-1'		=>	'product-1',
	'product-2'		=>	'product-2',
	'product-3'		=>	'product-3',
	'product-4'		=>	'product-4',
	'product-5'		=>	'product-5',
	'product-6'		=>	'product-6',
	'product-7'		=>	'product-7',
	'product-8'		=>	'product-8',
	'team-1'		=>	'team-1',
	'team-2'		=>	'team-2',
	'team-3'		=>	'team-3',
	'team-4'		=>	'team-4',
	'team-5'		=>	'team-5',
	'team-6'		=>	'team-6',
	'team-7'		=>	'team-7',
	'team-8'		=>	'team-8',
	'testimonial-1'	=>	'testimonial-1',
	'testimonial-2'	=>	'testimonial-2',
	'testimonial-3'	=>	'testimonial-3',
	'testimonial-4'	=>	'testimonial-4',
	'testimonial-5'	=>	'testimonial-5',
	'testimonial-6'	=>	'testimonial-6',
	'testimonial-7'	=>	'testimonial-7',
	'testimonial-8'	=>	'testimonial-8',
	'videos-1'		=>	'videos-1',		
	'videos-2'		=>	'videos-2',		
	'videos-3'		=>	'videos-3',		
	'videos-4'		=>	'videos-4',		
	'videos-5'		=>	'videos-5',		
	'videos-6'		=>	'videos-6',		
	'videos-7'		=>	'videos-7',		
	'videos-8'		=>	'videos-8',		
);
